name: Terraform CI/CD

on:
  push:
    branches:
      - Dev

  pull_request:
    branches:
      - Dev

  workflow_dispatch:
    inputs:
      environment:
        description: "Target Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - uat
          - prod

env:
  TF_VERSION: "1.15.8"
  ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}
  TF_LOG: INFO

permissions:
  contents: read

#################################################################################
# TERRAFORM PLAN
#################################################################################

jobs:

  terraform-plan:

    name: Terraform Plan

    runs-on:
      - self-hosted
      - Windows
      - X64

    timeout-minutes: 90

    environment: ${{ github.event.inputs.environment || 'dev' }}

    defaults:
      run:
        shell: powershell

    permissions:
      contents: read
      pull-requests: write

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

     # - name: Setup Terraform
      #  uses: hashicorp/setup-terraform@v3
       # with:
        #  terraform_version: ${{ env.TF_VERSION }}

      #- name: Verify Local Terraform
      #  shell: powershell
      #  run: |
       #   where.exe terraform
        #  terraform version

      - name: Install Terraform
        shell: powershell
        run: |
          $ProgressPreference = 'SilentlyContinue'

          Invoke-WebRequest `
          -Uri "https://releases.hashicorp.com/terraform/${{ env.TF_VERSION }}/terraform_${{ env.TF_VERSION }}_windows_amd64.zip" `
          -OutFile terraform.zip

          Expand-Archive terraform.zip -DestinationPath terraform -Force

          "$PWD\terraform" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

          .\terraform\terraform.exe version

      - name: Cache Terraform
        uses: actions/cache@v4
        with:
          path: .terraform
          key: terraform-${{ runner.os }}-${{ hashFiles('**/*.tf','**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
            }
      # - name: Verify Terraform Executable
      #   shell: powershell
      #   run: |
      #     Write-Host "PATH:"
      #     $env:PATH

      #     Write-Host ""
      #     Write-Host "Terraform location:"
      #     where.exe terraform

      #     Write-Host ""
      #     Get-Command terraform | Format-List *

      #     Write-Host ""
      #     terraform version
      - name: Verify GitHub Variables
        shell: powershell
        env:
          TF_VAR_github_owner: ${{ github.repository_owner }}
          TF_VAR_github_token: ${{ secrets.GH_ADMIN_TOKEN }}
        run: |
          Write-Host "====================================="
          Write-Host "GitHub Variables"
          Write-Host "====================================="

          Write-Host "Owner : $env:TF_VAR_github_owner"

          if ([string]::IsNullOrWhiteSpace($env:TF_VAR_github_token)) {
            Write-Error "GitHub Token is EMPTY!"
          }
          else {
            Write-Host "GitHub Token Length : $($env:TF_VAR_github_token.Length)"
          }
      - name: Terraform Init
        shell: powershell
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          terraform init `
            -backend-config="environments/${env:ENVIRONMENT}/backend.hcl"

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Install TFLint
        shell: powershell
        run: |
          $ProgressPreference = 'SilentlyContinue'

          Invoke-WebRequest `
            -Uri "https://github.com/terraform-linters/tflint/releases/latest/download/tflint_windows_amd64.zip" `
            -OutFile tflint.zip

          Expand-Archive -Path tflint.zip -DestinationPath .\tflint -Force

          $env:PATH += ";$PWD\tflint"

          .\tflint\tflint.exe --version

      - name: Initialize TFLint
        shell: powershell
        run: |
         .\tflint\tflint.exe --init

      - name: Run TFLint
        shell: powershell
        run: |
         .\tflint\tflint.exe

     # - name: Setup TFLint
     #   uses: terraform-linters/setup-tflint@v4

     # - name: Initialize TFLint
      #  run: tflint --init

      #- name: Run TFLint
       # run: tflint

     # - name: Run Checkov
     #   uses: bridgecrewio/checkov-action@master
     #   with:
      #    directory: .

      - name: Terraform Plan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

          TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}

          TF_VAR_github_owner: ${{ github.repository_owner }}
          TF_VAR_github_token: ${{ secrets.GH_ADMIN_TOKEN }}

          TF_VAR_runner_ssh_public_key: ${{ secrets.RUNNER_SSH_PUBLIC_KEY }}
          TF_VAR_runner_registration_token: ${{ secrets.RUNNER_REGISTRATION_TOKEN }}

        run: |
          terraform plan `
            -var-file="environments/${env:ENVIRONMENT}/terraform.tfvars" `
            -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ env.ENVIRONMENT }}
          path: tfplan
          retention-days: 5
      - name: Verify GitHub Variables
        shell: powershell
        env:
          TF_VAR_github_owner: ${{ github.repository_owner }}
          TF_VAR_github_token: ${{ secrets.GH_ADMIN_TOKEN }}
        run: |
          Write-Host "====================================="
          Write-Host "GitHub Variables"
          Write-Host "====================================="

          Write-Host "Owner : $env:TF_VAR_github_owner"

          if ([string]::IsNullOrWhiteSpace($env:TF_VAR_github_token)) {
            Write-Error "GitHub Token is EMPTY!"
          }
          else {
            Write-Host "GitHub Token Length : $($env:TF_VAR_github_token.Length)"
          }
#################################################################################
# TERRAFORM APPLY
#################################################################################

  terraform-apply:

    name: Terraform Apply

    needs: terraform-plan

    if: github.ref == 'refs/heads/Dev' && github.event_name != 'pull_request'

    runs-on:
      - self-hosted
      - Windows
      - X64

    timeout-minutes: 90

    environment: ${{ github.event.inputs.environment || 'dev' }}

    defaults:
      run:
        shell: powershell

    permissions:
      contents: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      # - name: Verify Terraform Installation
      #   shell: powershell
      #   run: |
      #    Write-Host "========================================"
      #    Write-Host "Terraform Installation"
      #    Write-Host "========================================"

      #    Write-Host ""
      #    Write-Host "PATH"
      #    Write-Host $env:PATH

      #    Write-Host ""
      #    Write-Host "Terraform Location"
      #    where.exe terraform

      #    Write-Host ""
      #    Get-Command terraform | Format-List *

      #    Write-Host ""
      #    Write-Host "Terraform Version"
      #    terraform version

      - name: Install Terraform
        shell: powershell
        run: |
          $ProgressPreference = 'SilentlyContinue'

          Invoke-WebRequest `
          -Uri "https://releases.hashicorp.com/terraform/${{ env.TF_VERSION }}/terraform_${{ env.TF_VERSION }}_windows_amd64.zip" `
          -OutFile terraform.zip

          Expand-Archive terraform.zip -DestinationPath terraform -Force

          "$PWD\terraform" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

          .\terraform\terraform.exe version

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Terraform Init
        shell: powershell
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          terraform version
          terraform init `
            -backend-config="environments/${env:ENVIRONMENT}/backend.hcl"

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-${{ env.ENVIRONMENT }}

      - name: Terraform Apply
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

          TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}

          TF_VAR_github_owner: ${{ github.repository_owner }}
          TF_VAR_github_token: ${{ secrets.GH_ADMIN_TOKEN }}

          TF_VAR_runner_ssh_public_key: ${{ secrets.RUNNER_SSH_PUBLIC_KEY }}
          TF_VAR_runner_registration_token: ${{ secrets.RUNNER_REGISTRATION_TOKEN }}

        run: |
          terraform apply -auto-approve tfplan

      - name: Terraform Output
        run: terraform output