############################################################
# Environment
############################################################

environment = "dev"
location    = "Canada Central"

common_tags = {
  Environment   = "DataEng"
  Project       = "Databricks"
  "Cost Center" = "3270"
  Compliance    = "-"
  Owner         = "PRESTO"
  "CN Number"   = "SIS-BC-IMP-6"
}

############################################################
# Existing Resource Groups
############################################################

existing_network_resource_group_name = "rg-presto-nonprod-de"
existing_data_resource_group_name    = "rg-presto-nonprod-de"
existing_infra_resource_group_name   = "prs-dataeng-cc-infra-rg"

############################################################
# Networking
############################################################

vnet_name = "prs-dataeng-cc-core-vnet"

subnets = {

  databricks_public = {
    name             = "prs-dataeng-cc-core-databricks-public-snet"
    nsg_name         = "prs-dataeng-cc-core-databricks-public-nsg"
    route_table_name = "prs-dataeng-cc-core-udr"
  }

  databricks_private = {
    name             = "prs-dataeng-cc-core-databricks-private-snet"
    nsg_name         = "prs-dataeng-cc-core-databricks-private-nsg"
    route_table_name = "prs-dataeng-cc-core-udr"
  }

  data = {
    name             = "prs-dataeng-cc-core-data-snet"
    nsg_name         = "prs-dataeng-cc-core-data-nsg"
    route_table_name = "prs-dataeng-cc-core-udr"
  }
}

databricks_public_subnet_key  = "databricks_public"
databricks_private_subnet_key = "databricks_private"
data_subnet_key               = "data"

############################################################
# Naming Standard
############################################################

naming_project  = "presto"
naming_instance = "001"

############################################################
# Storage - ADLS Gen2
############################################################

# Generated by local.tf:
# prestodatalakedev001

storage_containers = [
  "raw",
  "bronze",
  "silver",
  "gold"
]

storage_folders = [
  {
    container = "gold"
    path      = "data_management"
  }
]

storage_public_network_access_enabled = true

############################################################
# Azure Data Factory
############################################################

# Generated:
# adf-presto-dev-cc-001

adf_public_network_enabled = true

adf_contributor_group_object_ids = []
adf_reader_group_object_ids      = []

############################################################
# Azure Databricks
############################################################

# Generated:
# dbx-presto-dev-cc-001
#
# Managed RG:
# rg-dbx-presto-dev-managed-001

databricks_sku = "premium"

databricks_metastore_admin_object_ids = []

############################################################
# Azure Key Vault
############################################################

# Generated:
# kv-presto-dev-cc-001

key_vault_admin_object_ids          = []
key_vault_secrets_reader_object_ids = []

############################################################
# GitHub Repository
############################################################

repository_name = "presto_databricks"

repository_description = "Terraform IaC for the PRESTO Data Platform (DEV)"

repository_visibility = "private"

required_approving_review_count = 1

enable_branch_protection = false

############################################################
# GitHub Self-hosted Runners
############################################################

#enable_github_runners = true

#runner_vmss_name = "prs-dataeng-gh-runners"

#runner_vm_size = "Standard_DC2s_v3"

#runner_instance_count = 2

#runner_autoscale_min = 1
#runner_autoscale_max = 5

############################################################
# Sensitive Values
############################################################

# DO NOT place secrets in this file.
#
# Supply these using GitHub Secrets or TF_VAR_* variables:
#
# azure_subscription_id
# azure_tenant_id
# azure_client_id
# azure_client_secret
# github_owner
# github_token
# runner_ssh_public_key
# runner_registration_token